export const ABI = [
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "usersActiveX3Levels",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "balances",
    inputs: [{ type: "address", name: "", internalType: "address" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "idToAddress",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "lastUserId",
    inputs: [],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "userIds",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isUserExists",
    inputs: [{ type: "address", name: "user", internalType: "address" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "payable",
    payable: true,
    outputs: [],
    name: "registrationExt",
    inputs: [
      { type: "address", name: "referrerAddress", internalType: "address" },
    ],
    constant: false,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [
      { type: "address", name: "", internalType: "address" },
      { type: "address[]", name: "", internalType: "address[]" },
      { type: "bool", name: "", internalType: "bool" },
    ],
    name: "usersX3Matrix",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [
      { type: "address", name: "", internalType: "address" },
      { type: "address[]", name: "", internalType: "address[]" },
      { type: "address[]", name: "", internalType: "address[]" },
      { type: "bool", name: "", internalType: "bool" },
      { type: "address", name: "", internalType: "address" },
    ],
    name: "usersX6Matrix",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [
      { type: "uint256", name: "id", internalType: "uint256" },
      { type: "address", name: "referrer", internalType: "address" },
      { type: "uint256", name: "partnersCount", internalType: "uint256" },
    ],
    name: "users",
    inputs: [{ type: "address", name: "", internalType: "address" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "usersActiveX6Levels",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "payable",
    payable: true,
    outputs: [],
    name: "buyNewLevel",
    inputs: [
      { type: "uint8", name: "matrix", internalType: "uint8" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: false,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "registrationCost",
    inputs: [],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "findFreeX6Referrer",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "levelPrice",
    inputs: [{ type: "uint8", name: "", internalType: "uint8" }],
    constant: true,
  },
  {
    type: "function",
    stateMutability: "view",
    payable: false,
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "findFreeX3Referrer",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "uint8", name: "level", internalType: "uint8" },
    ],
    constant: true,
  },
  {
    type: "constructor",
    stateMutability: "nonpayable",
    payable: false,
    inputs: [{ type: "address", name: "owner", internalType: "address" }],
  },
  { type: "fallback", stateMutability: "payable", payable: true },
  {
    type: "event",
    name: "Registration",
    inputs: [
      { type: "address", name: "user", internalType: "address", indexed: true },
      {
        type: "address",
        name: "referrer",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "userId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "referrerId",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Reinvest",
    inputs: [
      { type: "address", name: "user", internalType: "address", indexed: true },
      {
        type: "address",
        name: "currentReferrer",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "caller",
        internalType: "address",
        indexed: true,
      },
      { type: "uint8", name: "matrix", internalType: "uint8", indexed: false },
      { type: "uint8", name: "level", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Upgrade",
    inputs: [
      { type: "address", name: "user", internalType: "address", indexed: true },
      {
        type: "address",
        name: "referrer",
        internalType: "address",
        indexed: true,
      },
      { type: "uint8", name: "matrix", internalType: "uint8", indexed: false },
      { type: "uint8", name: "level", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewUserPlace",
    inputs: [
      { type: "address", name: "user", internalType: "address", indexed: true },
      {
        type: "address",
        name: "referrer",
        internalType: "address",
        indexed: true,
      },
      { type: "uint8", name: "matrix", internalType: "uint8", indexed: false },
      { type: "uint8", name: "level", internalType: "uint8", indexed: false },
      { type: "uint8", name: "place", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MissedEthReceive",
    inputs: [
      {
        type: "address",
        name: "receiver",
        internalType: "address",
        indexed: true,
      },
      { type: "address", name: "from", internalType: "address", indexed: true },
      { type: "uint8", name: "matrix", internalType: "uint8", indexed: false },
      { type: "uint8", name: "level", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SentExtraEthDividends",
    inputs: [
      { type: "address", name: "from", internalType: "address", indexed: true },
      {
        type: "address",
        name: "receiver",
        internalType: "address",
        indexed: true,
      },
      { type: "uint8", name: "matrix", internalType: "uint8", indexed: false },
      { type: "uint8", name: "level", internalType: "uint8", indexed: false },
    ],
    anonymous: false,
  },
];

export const ADDRESS = "0xe1bBb63e8cAC9361f0c07Ad6AEE12c2893D42735";

export const OWNER = "0xf2aA26723ed7b099845afE69FA4929A46BC00245";

export const BASE_URL = "https://amnext.vercel.app/";

// https://mumbai-explorer.matic.today/address/0xe1bBb63e8cAC9361f0c07Ad6AEE12c2893D42735/contracts
